---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: namespace-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""

---
kind: ConfigMap
apiVersion: v1

metadata:
  name: merlin-sos-config
data:
  application.json:
    ' {
    "mil.afdcgs.merlin.sos.kafka.bootstrap-server": "kafka.merlin-phase1.svc.cluster.local:9092",
    "mil.afdcgs.merlin.sos.kafka.partition-count": "1",
    "mil.afdcgs.merlin.sos.kafka.replica-count": "1"
  }'

---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: merlin-sos
  labels:
    name: merlin-sos
spec:
  replicas: 1
  selector:
    matchLabels:
      name: merlin-sos
  template:
    metadata:
      labels:
        name: merlin-sos
    spec:
      containers:
        - name: test-app
          image: registry.local/merlin-sos:latest
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: merlin-sos-config
                  key: application.json
